name: build ios-dev

on:
  workflow_dispatch:

jobs:
  build_ios:
    runs-on: macos-latest
    env:
      SHEME: Runner
      BUILD_CONFIGURATION: Release
      TEAM_ID: ${{ secrets.TEAM_ID }}
      PROVISIONING_PROFILE: ${{ secrets.PROVISIONING_PROFILE }}
      CODE_SIGN_IDENTITY: ${{ secrets.CODE_SIGN_IDENTITY }}

    steps:
      - name: Checkout the code
        uses: actions/checkout@v2

      - name: Prepare for build
        run: |
          KEYCHAIN_PASSWORD=${{ secrets.KEYCHAIN_PASSWORD }}
          SSH_PRIVATE_KEY=${{ secrets.SSH_PRIVATE_KEY }}
          APP_GIT_URL=${{ secrets.APP_GIT_URL }}
          echo "$SSH_PRIVATE_KEY" | base64 -d > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa
          ssh-add ~/.ssh/id_rsa
          echo "----------------"
          cat ~/.ssh/id_rsa
          echo "----------------"
          git clone "$APP_GIT_URL"
          # 截取仓库名
          repo_name=$(basename "$APP_GIT_URL" .git)
          mv "$repo_name"/* .
          cd $repo_name
          echo "当前目录：$(pwd)"
          cd .github/cert
          ls -a
          mkdir .github/cert
          mv "$repo_name"/.github/cert/* .github/cert/
          PP_WIDGET_PATH=.github/cert/IMDevPPWidget.mobileprovision
          PP_PATH=.github/cert/IMDevPP.mobileprovision
          #执行构建
          #Install the Apple certificate and provisioning profile
          KEYCHAIN_PATH=$RUNNER_TEMP/app-signing.keychain-db
          security create-keychain -p "$KEYCHAIN_PASSWORD" "$KEYCHAIN_PATH"
          security set-keychain-settings -lut 21600 "$KEYCHAIN_PATH"
          security unlock-keychain -p "$KEYCHAIN_PASSWORD" "$KEYCHAIN_PATH"
          security import .GitHub/cert/cert.p12 -P "${{ secrets.P12_PASSWORD }}" -A -t cert -f pkcs12 -k $KEYCHAIN_PATH
          security list-keychain -d user -s $KEYCHAIN_PATH
          mkdir -p ~/Library/MobileDevice/Provisioning\ Profiles
          cp "$PP_PATH" ~/Library/MobileDevice/Provisioning\ Profiles
          cp "$PP_WIDGET_PATH" ~/Library/MobileDevice/Provisioning\ Profiles

      - name: Install and set Flutter version
        uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.7.5'

      - name: Restore packages
        run: flutter pub get

      - name: pod repo update
        run: pod repo update

      - name: Build Flutter
        run: flutter build ios --release --no-codesign

      - name: Build resolve Swift dependencies
        run: xcodebuild -resolvePackageDependencies -workspace ios/Runner.xcworkspace -scheme ${{ env.SHEME }} -configuration ${{ env.BUILD_CONFIGURATION }}

      - name: Build xArchive
        run: |
          xcodebuild -workspace ios/Runner.xcworkspace -scheme ${{ env.SHEME }} -configuration ${{ env.BUILD_CONFIGURATION }} DEVELOPMENT_TEAM=${{ env.TEAM_ID }} -sdk 'iphoneos16.2' -destination 'generic/platform=iOS' -archivePath build-output/app.xcarchive PROVISIONING_PROFILE=${{ env.PROVISIONING_PROFILE }} clean archive CODE_SIGN_IDENTITY="${{ env.CODE_SIGN_IDENTITY }}"
      - name: Export ipa
        run: xcodebuild -exportArchive -archivePath build-output/app.xcarchive -exportPath build-output/ios -exportOptionsPlist ios/ExportOptions.plist

      - name: push ipa to server
        uses: appleboy/scp-action@master
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          key: ${{ secrets.KEY }}
          port: ${{ secrets.PORT }}
          source: build-output/ios/
          target: /home/ios
